const bootLines=['[ OK ] kernel initialized','[ OK ] loading developer modules','[ OK ] mounting project database','[ OK ] establishing secure interface','[ OK ] identity verified','ACCESS GRANTED.'];
const bootText=document.querySelector('#bootText'),enter=document.querySelector('#enter');let bi=0;
function boot(){if(bi<bootLines.length){bootText.textContent+=bootLines[bi++]+'\n';setTimeout(boot,220)}else enter.classList.remove('hidden')}boot();
enter.onclick=()=>{document.querySelector('#boot').remove();document.querySelector('#app').classList.remove('hidden');typeText()};
const phrases=['Developer. Technology enthusiast.','Building systems. Creating experiences.','Code // Hardware // Creative'];let pi=0,ci=0,del=false;
function typeText(){const el=document.querySelector('#typed'),s=phrases[pi];el.textContent=s.slice(0,ci);if(!del&&ci<s.length)ci++;else if(del&&ci>0)ci--;else if(ci===s.length){del=true;return setTimeout(typeText,1300)}else{del=false;pi=(pi+1)%phrases.length}setTimeout(typeText,del?28:55)}
document.querySelector('#year').textContent=new Date().getFullYear();
const out=document.querySelector('#output'),cmd=document.querySelector('#cmd');const commands={help:'Comandos: whoami, skills, projects, experience, contact, clear',whoami:'Leandro Alves // Developer & Technology enthusiast // São Vicente, SP',skills:'HTML · CSS · JavaScript · Python · Lua · Node.js · Hardware · Photoshop · Inteligência Artificial · Gestão de Projetos · Marketing com IA',projects:'ABADDON // Game Development // Digital Design // AI-assisted Projects & Marketing',experience:'Estoquista, Casa de rações [02.2025 → 04.2025] // Ensino Médio Completo',contact:'leandroalvscruz@gmail.com'};
cmd.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const v=cmd.value.trim().toLowerCase();const p=document.createElement('p');p.innerHTML='<strong>visitor@leandro:~$</strong> '+escapeHtml(cmd.value);out.appendChild(p);if(v==='clear')out.innerHTML='';else{const r=document.createElement('p');r.textContent=commands[v]||'command not found: '+v;out.appendChild(r)}cmd.value='';out.scrollTop=out.scrollHeight});
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const canvas=document.querySelector('#matrix'),ctx=canvas.getContext('2d');let cols,drops;function resize(){canvas.width=innerWidth;canvas.height=innerHeight;cols=Math.floor(canvas.width/18);drops=Array(cols).fill(1)}resize();addEventListener('resize',resize);setInterval(()=>{ctx.fillStyle='rgba(5,8,6,.12)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#5cff8d';ctx.font='12px monospace';drops.forEach((y,i)=>{const t=Math.random()>.5?'1':'0';ctx.fillText(t,i*18,y*18);if(y*18>canvas.height&&Math.random()>.98)drops[i]=0;drops[i]++})},65);
